### ISSUE TITLE
"TypeError: Cannot read property 'on' of undefined"

### ISSUE THREAD

**Issue by rderimay** [konvajs/vue-konva#14] opened 2018-05-04 08:42 UTC
I made a very simple project where I wanted to test vue-konva I get the following:
``` 
Error in mounted hook: "TypeError: Cannot read property 'on' of undefined"
```

My component has a very simple template:
```
<template>
    <v-stage :config="configKonva">
        <v-layer>
            <v-circle :config="configCircle"></v-circle>
        </v-layer>
    </v-stage>
</template>
```

and data:

```
   data () {
      return {
        configKonva: {
          width: 200,
          height: 200,
        },
        configCircle: {
          x: 100,
          y: 100,
          radius: 70,
          fill: 'red',
          stroke: 'black',
          strokeWidth: 4,
        },
        icons: {},
      }
    },
```

the google chrome trace looks like that:
```
TypeError: Cannot read property 'on' of undefined
    at VueComponent.mounted (admin.js:84063)
    at callHook (admin.js:90305)
    at Object.insert (admin.js:91542)
    at invokeInsertHook (admin.js:93344)
    at Vue.patch [as __patch__] (admin.js:93563)
    at Vue._update (admin.js:90044)
    at Vue.updateComponent (admin.js:90172)
    at Watcher.get (admin.js:90526)
    at new Watcher (admin.js:90515)
    at mountComponent (admin.js:90179)
```

admin being the name of my app.

Any idea where does the problem comes from? It looks almost as some vue-konva components would not be correctly registered, but it that case, I would get a different error message from Vue.

I imported vue-konva with `import` and `Vue.use(VueKonva)`...

**Comment by Ldoppea** [comment] 2018-09-11 15:49
Hi,

Can one of you give more details on how to reproduce the bug? (starting from project generation)

Did you create the project with vue-cli? Or from scratch? What are the version used (vue and vue-cli)?

If you success to reproduce the problem with https://codesandbox.io it would be very helpful. Or maybe using a github project?

**Comment by nanookon** [comment] 2018-11-01 08:08
I'm getting the same error.
I've tried to add konva to an existing project. 
vue version 2.5.14, vue-cli version 2.9.6

**Comment by jon-ht** [comment] 2018-11-10 12:08
Hi,

I have an ElectronJS project and I also ran into this bug. To make it work, I had to add `vue-konva` to my `whiteListedModules` in webpack config file (`webpack.renderer.config.js`)

```js
/**
 * List of node_modules to include in webpack bundle
 *
 * Required for specific packages like Vue UI libraries
 * that provide pure *.vue files that need compiling
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals
 */
let whiteListedModules = ['vue', 'vuetify', 'vue-konva'];

let rendererConfig = {
  devtool: '#cheap-module-eval-source-map',
  entry: {
    renderer: path.join(__dirname, '../src/renderer/main.js')
  },
  externals: [
    ...Object.keys(dependencies || {}).filter(d => !whiteListedModules.includes(d))
  ],
  ...
}
```

I hope it can help you too

**Comment by qq5050595531** [comment] 2019-04-13 03:22
@jon-ht thx, It works.

**Comment by Yeselimar** [comment] 2019-04-21 17:21
Hi, any solution for vuejs?  I'm currently running into the same problem :-(

**Comment by lavrton** [comment] 2019-07-31 08:28
Closing the issue for now, because I don't see ways to reproduce the issue.

If someone has this bug - please, provide a demo.

**Closed by lavrton** 2019-07-31 08:28 UTC

**Comment by lvbirui** [comment] 2019-09-24 02:23
i have the same problem like jon-ht ,but it dose not work....@jon-ht

**Comment by lvbirui** [comment] 2019-09-24 02:37
> i have the same problem like jon-ht ,but it dose not work....@jon-ht

@jon-ht  's solution is worked, i put the  'vue-konva' and restart my project (close the vscode and restart),and it  works.
