### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by ewen-lbh** [konvajs/vue-konva#123] opened 2020-09-22 15:39 UTC
Hi! Is Vue 3 support planned?

**Comment by tuannguyenminh2086** [comment] 2020-09-23 03:10
I think you can use it now with composition api. that's no problem

**Comment by raphaelsoul** [comment] 2020-09-27 05:48
vite throw this error, also no cmd styled entry file found in node_modules

```
[vite] Dep optimization failed with error:
[vite]: Rollup failed to resolve import "konva" from "node_modules/vue-konva/umd/vue-konva.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
Error: [vite]: Rollup failed to resolve import "konva" from "node_modules/vue-konva/umd/vue-konva.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
    at Object.onwarn (/Users/raphaelsoul/projects/zuma/wang-weifeng/datashow/v3/node_modules/vite/dist/node/build/index.js:70:19)
    at Object.onwarn (/Users/raphaelsoul/projects/zuma/wang-weifeng/datashow/v3/node_modules/rollup/dist/shared/rollup.js:19393:20)
    at ModuleLoader.handleResolveId (/Users/raphaelsoul/projects/zuma/wang-weifeng/datashow/v3/node_modules/rollup/dist/shared/rollup.js:18268:26)
    at /Users/raphaelsoul/projects/zuma/wang-weifeng/datashow/v3/node_modules/rollup/dist/shared/rollup.js:18258:22
    at async Promise.all (index 2)
    at async ModuleLoader.fetchStaticDependencies (/Users/raphaelsoul/projects/zuma/wang-weifeng/datashow/v3/node_modules/rollup/dist/shared/rollup.js:18256:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/Users/raphaelsoul/projects/zuma/wang-weifeng/datashow/v3/node_modules/rollup/dist/shared/rollup.js:18233:9)
    at async Promise.all (index 3) {

```

**Comment by Dylan-Chapman** [comment] 2020-10-05 17:15
Adding to this - I get the error `Uncaught TypeError: Cannot read property 'component' of undefined` (from the line `var Stage = (external_root_Vue_commonjs2_vue_commonjs_vue_amd_vue_default.a.component('v-stage', {`) when trying to use VueKonva both via `createApp(App).use(VueKonva).mount("#app")` and CDN with Vue 3.

**Comment by mazoqui** [comment] 2020-10-05 18:56
I get same error!

**Comment by lavrton** [comment] 2020-10-22 15:04
I am planning to support vue@3. For now, I am waiting for an official stable release.
If someone needs it sooner - feel free to make a fix and make a Pull Request.

**Comment by OEvgeny** [comment] 2020-10-24 12:23
Hi @lavrton, thank you for the project!

Happy to tell that Vue [v3.0.2](https://github.com/vuejs/vue-next/releases/tag/v3.0.2) is officially released and should be pretty stable after 13 RCs and two minor releases

**Comment by cylazhm** [comment] 2020-12-01 05:13
Is vue@3 still not supported yet?

**Comment by lavrton** [comment] 2020-12-02 15:54
I do have plans for better v3 support. For now, I don't want to fix the current `vue-konva` architecture. I have plans for a major rewrite with function via custom renderer. It should work more efficiently.

**Comment by cristianvasquez** [comment] 2021-01-13 11:54
> I think you can use it now with composition api. that's no problem
hi @tuannguyenminh2086 
Do you have any example of Konva using the composition API?

**Comment by ymebrugts** [comment] 2021-03-24 14:49
Same error: 
`Uncaught TypeError: Cannot read property 'component' of undefined`

> I do have plans for better v3 support. For now, I don't want to fix the current `vue-konva` architecture. I have plans for a major rewrite with function via custom renderer. It should work more efficiently.
Why mention "better v3 support" when it literally has 0 support for Vue3? Unless I'm misunderstanding and there is a way to make it work with v3?

**Comment by lavrton** [comment] 2021-03-24 14:51
Well, according to my logic, anything that is not 0 is better.

**Comment by Amar-Gill** [comment] 2021-03-28 13:46
I get this error when I write `import VueKonva from 'vue-konva'`:
`Uncaught TypeError: external_root_Vue_commonjs2_vue_commonjs_vue_amd_vue_default.a is undefined
    require_vue_konva vue-konva.js:304
    __webpack_require__ vue-konva.js:34
    require_vue_konva vue-konva.js:111
    __webpack_require__ vue-konva.js:34
    require_vue_konva vue-konva.js:98
    require_vue_konva vue-konva.js:101
    webpackUniversalModuleDefinition vue-konva.js:7
    require_vue_konva vue-konva.js:14
    __commonJS chunk-LV3Z5TDC.js:7
    <anonymous> vue-konva:1
vue-konva.js:304:42
    require_vue_konva vue-konva.js:304
    __webpack_require__ vue-konva.js:34
    require_vue_konva vue-konva.js:111
    __webpack_require__ vue-konva.js:34
    require_vue_konva vue-konva.js:98
    require_vue_konva vue-konva.js:101
    webpackUniversalModuleDefinition vue-konva.js:7
    require_vue_konva vue-konva.js:14
    __commonJS chunk-LV3Z5TDC.js:7
    <anonymous> vue-konva:1
    InnerModuleEvaluation self-hosted:2379
    InnerModuleEvaluation self-hosted:2379
    evaluation self-hosted:2330`

**Comment by alew3** [comment] 2021-04-11 14:36
> I'm using vue 3.0.5. I get this error when I write `import VueKonva from 'vue-konva'` in main.js:
> 
> ```
> Uncaught TypeError: external_root_Vue_commonjs2_vue_commonjs_vue_amd_vue_default.a is undefined
>     require_vue_konva vue-konva.js:304
>     __webpack_require__ vue-konva.js:34
>     require_vue_konva vue-konva.js:111
>     __webpack_require__ vue-konva.js:34
>     require_vue_konva vue-konva.js:98
>     require_vue_konva vue-konva.js:101
>     webpackUniversalModuleDefinition vue-konva.js:7
>     require_vue_konva vue-konva.js:14
>     __commonJS chunk-LV3Z5TDC.js:7
>     <anonymous> vue-konva:1
> vue-konva.js:304:42
>     require_vue_konva vue-konva.js:304
>     __webpack_require__ vue-konva.js:34
>     require_vue_konva vue-konva.js:111
>     __webpack_require__ vue-konva.js:34
>     require_vue_konva vue-konva.js:98
>     require_vue_konva vue-konva.js:101
>     webpackUniversalModuleDefinition vue-konva.js:7
>     require_vue_konva vue-konva.js:14
>     __commonJS chunk-LV3Z5TDC.js:7
>     <anonymous> vue-konva:1
>     InnerModuleEvaluation self-hosted:2379
>     InnerModuleEvaluation self-hosted:2379
>     evaluation self-hosted:2330
> ```

same here, I don't think it has vue3 support I guess.

**Comment by myoneflag** [comment] 2021-07-07 13:02
Any luck V3 not supported vue-konva?
Got the same error.
![image](https://user-images.githubusercontent.com/47198076/124763419-3b3bcb80-df34-11eb-8684-e4041f8df209.png)

**Comment by rtbo** [comment] 2021-07-29 10:15
There is the `vue3-konva` npm package. I don't know if it is an official konvajs package or a fork, but it seems to work for me with `vue-3.0.5`

**Comment by piscis** [comment] 2021-08-20 10:31
> There is the `vue3-konva` npm package. I don't know if it is an official konvajs package or a fork, but it seems to work for me with `vue-3.0.5`

its a fork from this repository and not official: https://github.com/vunamhung/vue-konva/commit/2a9abd39844a46d7e1af8dc2d5275eecbce077c0

**Comment by FaultErrorFailure92** [comment] 2021-09-10 16:48
> There is the `vue3-konva` npm package. I don't know if it is an official konvajs package or a fork, but it seems to work for me with `vue-3.0.5`

How did you get it to work?

I tried to create a boot-file but I'm not lucky


`import { boot } from 'quasar/wrappers'
import VueKonva from 'vue3-konva';

app.use(VueKonva);
// "async" is optional;
// more info on params: https://v2.quasar.dev/quasar-cli/boot-files
export default ({ /* app, router, store */ }) => {
  return new Promise((resolve, reject) => {
    // do something

  })
}`

**Comment by rtbo** [comment] 2021-09-13 09:37
@FaultErrorFailure92 I wrote too soon. When I tested I saw a scene rendered and wrote the message.
May have been due to dev-server cache or whatever. Sorry for confusion.
I have switched my code to render dynamic SVG. This works very well with Vue and is more than enough for my need.

**Comment by geoffgscott** [comment] 2021-11-05 14:58
A composition API based approach for Vue3 was merged. There is still two outstanding bugs that are causing test failures though:

- Conditional layers (v-if/v-for) causes the Vue internals bug. This is a hard one to debug but only occurs with layers not with nested conditionals (v-if on a shape inside  a layer).
- Reactive event handlers. With the move to Vue 3.1 and up something there is a quirk with Vue-Konva reactivity where you can't add a listener dynamically if it was undefined to begin with. Weirdly null works so if you need to change the listener on a shape dynamically I recommend defining it as `null` or `() => null` and then reactivity should work as expected. 

Any insight on either error would be super helpful. 

If you want to test this passes:
```javascript
  it('can update component events', async() => {
    const wrap = mount({
      template: `
        <v-stage :config="stage">
          <v-layer>
            <v-rect ref="rect" :config="{width: 300}" @click="click" />
          </v-layer>
        </v-stage>
      `,
      props: ['click'],
      data() {
        return {
          stage: {
            width: 300,
            height: 400,
          },
        };
      },
    }, { propsData: { click: null } }); // INITIALLY NULL

    const rect = wrap.vm.$refs.rect.getNode();
    expect(rect.eventListeners.click).to.equal(undefined);
    const handler = () => {};
    await wrap.setProps({ click: handler });
    expect(rect.eventListeners.click.length).to.equal(1);
    await wrap.setProps({ click: undefined });
    expect(rect.eventListeners.click).to.equal(undefined);
  });
```
But this fails:
```javascript
  it('can update component events', async() => {
    const wrap = mount({
      template: `
        <v-stage :config="stage">
          <v-layer>
            <v-rect ref="rect" :config="{width: 300}" @click="click" />
          </v-layer>
        </v-stage>
      `,
      props: ['click'],
      data() {
        return {
          stage: {
            width: 300,
            height: 400,
          },
        };
      },
    }, { propsData: { click: undefined } }); // INITIALLY UNDEFINED

    const rect = wrap.vm.$refs.rect.getNode();
    expect(rect.eventListeners.click).to.equal(undefined);
    const handler = () => {};
    await wrap.setProps({ click: handler });
    expect(rect.eventListeners.click.length).to.equal(1);
    await wrap.setProps({ click: undefined });
    expect(rect.eventListeners.click).to.equal(undefined);
  });
```

**Comment by lavrton** [comment] 2021-11-05 15:02
Thanks for the updates from @geoffgscott in https://github.com/konvajs/vue-konva/pull/172 I just released `vue-konva@3.0.0-0`. It should support `vue@3`. I don't think it will work with `vue@2`.

I didn't deeply test it by myself. Please try it.
Demo: https://codesandbox.io/s/vue-konva-with-vue-3-88o9o

**Comment by boboldehampsink** [comment] 2021-12-21 07:18
Thanks @lavrton, tested it and found a little issue: https://github.com/konvajs/vue-konva/pull/172#issuecomment-996565543

**Comment by lavrton** [comment] 2021-12-21 18:45
@boboldehampsink can you make a reproducible example? My codesandbox above work on.

**Comment by boboldehampsink** [comment] 2021-12-22 07:06
@lavrton when I remove `ref="layer"` from `v-layer` in your example I see the error:

<img width="1196" alt="Screen Shot 2021-12-22 at 08 05 41" src="https://user-images.githubusercontent.com/378974/147050158-1a01b426-2727-4b1b-8e4a-7315612f6f59.png">

**Comment by boboldehampsink** [comment] 2022-01-12 06:39
@lavrton any chance of fixing this? We can't use konva for vue 3 because of this.

**Comment by lavrton** [comment] 2022-01-12 18:25
I am not certain how to reproduce it. I saw this issue once when I tried to remove `ref="layer"` from my example above. But it was gone when I reload, so I guess it was related to hot reload.

**Comment by boboldehampsink** [comment] 2022-01-13 07:11
@lavrton I think vue-konva should just allow the use of `<template>` tags, as they do not render html anyway. It would fix this issue.

**Comment by boboldehampsink** [comment] 2022-02-15 14:26
@lavrton I provided a fix in #185

**Comment by lavrton** [comment] 2022-03-21 16:23
There are two issues are still there with `vue-konva` for `vue@3`.

Two tests in `index.test.js`

1. `checking for loop order in layers`
2. `no DOM events`

**Comment by DavidVaness** [comment] 2022-03-30 12:35
@lavrton Our team needs Konva for Vue 3 and would be willing to invest some time to make it work. If there are any more details you can give to make it work... We will try to help you

**Comment by lavrton** [comment] 2022-03-30 17:08
@DavidVaness `vue-konva@3` with `vue@3` support is already published. Try it. How does it work for you?

From my experience, it mostly works. But stage events are not working correctly. They double trigger for native DOM event. As a workaround, it is possible to filter them inside event callback.

**Comment by DavidVaness** [comment] 2022-03-30 17:43
Great, we will try it and provide feedback. If you need help, let me know

**Comment by p-clerc** [comment] 2022-05-03 12:15
Hello, 

I am using vue-konva (3.0.0) with Vue (3.2.33) and Vite (2.9.7). 

It works well in development mode (using `vite` command), but in production (after `vite build`) the css of my application is completely broken. I have no error in the browser console, nor during the build process. 

The import of vue-konva in the main.ts file generates the problem, even if I don't use the konva plugin in my app (even if I don't call `app.use(VueKonva)`). 

Do you have some advices or vite specific configurations in order to avoid the problem ? 
Or is it preferable to compile my application using vue-konva with webpack and vue-cli ?

**Comment by lavrton** [comment] 2022-05-03 13:24
@p-clerc make a minimal repository to reproduce the issue.

**Comment by p-clerc** [comment] 2022-05-06 09:45
Hello @lavrton  

In fact my problem is more complex, I resolved the problem on my computer but in a docker container it still appears. 
I do not master well vite and esbuild, but it seems that the build environment has a effect on the CSS result. 

Here is a little repo with which you can reproduce the problem. As said removing the usage of vue-konva solve the issue but it could come from vite or esbuild. 

https://github.com/p-clerc/vue3-template

Thanks for you help

**Comment by lavrton** [comment] 2022-05-06 15:53
I am not sure what I can do from `vue-konva` side. The repo works ok for me locally (without docker). And I don't want to fight with docker.

**Comment by p-clerc** [comment] 2022-05-09 12:04
> I am not sure what I can do from `vue-konva` side. The repo works ok for me locally (without docker). And I don't want to fight with docker.

Thank you @lavrton  for your time, in fact I have found another workaround with Vuetify theme customization. I think my problem was not related to konvas but permits to shown the Vuetify bug. As I use aplha/beta versions of Vuetify and there releated vite plugins, this kind of bug could appear.

**Comment by daitenshiren** [comment] 2022-10-17 10:14
Good day, @lavrton I'm having this weird issue with layers moving up or down the array. i'm using vue 3 it was originally written in composition api but I thought that was what causing the bug so i made a small demo using option api but still getting the error. 
I'm wondering if you can take a look at it. I have created a small demo. https://codesandbox.io/s/crazy-maria-l6rd11?file=/src/App.vue

**Comment by lavrton** [comment] 2022-10-17 21:06
@daitenshiren I think the issue with your code is that you don't use keys correctly.
I changed it a bit into:

`<v-group v-for="(item, i) in stage.elements" :key="item.config.id">`

Looks like it works ok now: https://codesandbox.io/s/wizardly-resonance-yckfhe

**Closed** 2024-08-11 22:27 UTC
