### ISSUE TITLE
How to fire event after `v-stage` rerenders

### ISSUE THREAD

**Issue by modermo** [konvajs/vue-konva#90] opened 2019-11-24 07:37 UTC
I have a stage that I'm dynamically generating from a VueX model, as is recommended in the docs. 

The problem is that when I update the model from outside the canvas (e.g. an input of a shape's `x` value for example), any watchers of the model fire BEFORE the canvas has a chance to update.

Thus, I'm wondering if there is some sort of an event that can be fired AFTER `v-stage` rerenders/redraws as a result of a model/data update. Something like `@redraw` could be useful.

**Comment by lavrton** [comment] 2019-11-25 15:46
Can you clarify why do you need this event?

**Comment by lavrton** [comment] 2019-12-24 15:25
Closing as no info.

**Closed by lavrton** 2019-12-24 15:25 UTC

**Comment by wxfred** [comment] 2020-10-17 08:27
@lavrton Hi, I have the same question.
In my project, there is a front v-stage for users to design. This front v-stage has a scene region, and supports zoom-in, zoom-out, like photoshop dose.
And there is another v-stage which is hidden behind for generating whole scene region to a png.
Usually, the scene is very large, making the hidden v-stage sync with the front one is low performance. So, after users click the save button, I transfer the data of the front one to the hidden one, then invoke toDataURL method. But the reconstruction of the hidden v-stage is not finished, so I got a blank png. I tried using $nextTick, not working. Maybe setTimeout with a long period can solve the problem, but, more nodes in stage means more redraw time.
Is it possible to provide a stage event like @drawend?
Or dose Konva has some other features for solving my background-png-saving demand.
Imagine that, a user chooses 3 layers, then clicks the save button, finally he will get 3 pngs which are the same size of the layers for each.

**Comment by lavrton** [comment] 2020-10-17 12:57
@wxfred why you don't just use `toDataURL()` on the main visible stage or on any its children?

**Comment by wxfred** [comment] 2020-10-17 13:28
@lavrton I tried once, if the main stage is showing the half of the scene, `toDataURL` only get what is visible on that stage.
My stage is the same size with the browser without scrollbar, and I use a simple camera object to simulate the transform of the scene.
```
<v-stage :config="{
      x: stagex,
      y: stagey,
      width: width,
      height: height,
      offsetX: camera.x - width / 2.0 / camera.scale,
      offsetY: camera.y - height / 2.0 / camera.scale,
      scaleX: camera.scale,
      scaleY: camera.scale,
      draggable: edit,
    }" ref="stage"
```
I can only change the camera attrs when mouse events have been received
```
  data() {
    return {
      id: 'pageview-' + uuidv4(),
      width: 0.0,
      height: 0.0,
      stagex: 0,
      stagey: 0,
      camera: {
        x: 0.0,
        y: 0.0,
        scale: 1.0,
      },
```

So, the problem is some part of the scene dose not shown on the stage when save button is clicked, and I want to export whole stage with its full size.

By the way, after hours trying, I found out $nextTick will help if all images were pre-loaded.
If there is a method to export the png of nodes which even are not shown on the stage would be very very helpful.

**Comment by lavrton** [comment] 2020-10-17 13:40
You can control what to show in `toDataURL()` with options `x`, `y`, `width`, `height`. So it doesn't matter what is visible in the viewport.

**Comment by wxfred** [comment] 2020-10-17 13:47
Not viewport, I mean some part of the scene is out of the canvas.

**Comment by lavrton** [comment] 2020-10-18 03:44
Again, you can export any size. Even if your stage is small, you can export its content into a large image (so all objects are visible).

**Comment by wxfred** [comment] 2020-10-18 13:36
@lavrton Thanks! I tried with setting options width, height in a 1x1 stage, got a full size png of my scene.
```
layer.toDataURL({
    width: scene.w,
    height: scene.h,
});
```
